#pragma once
#include <optional>
#include <memory>
#include <functional>
#include <unordered_set>
#include <vector>
#include <format>
#include "grammar.hpp"
#include "lexer.hpp"
#include "utils.hpp"
#include "ast.hpp"

namespace jc
{
  using namespace grammar;

  namespace parser
  {
    struct ParserError
    {
      u64 token_position;
      u32 line_number;
      std::string message;
      std::string token_found;
      std::string expected_tokens;

      ParserError(u64 pos, u32 line, const std::string &msg, const std::string &found, const std::string &expected)
          : token_position(pos), line_number(line), message(msg), token_found(found), expected_tokens(expected) {}

      std::string to_string() const
      {
        return std::format("[ERRO SINTÁTICO] - Linha {} (coluna {}) - {} | Encontrado: {} | Esperava: {}", line_number, token_position, message, token_found, expected_tokens);
      }
    };

    /**
     * \brief An Earley item, containing 1 grammar production, its source column and the current symbol being read, i.e., the dot index.
     */
    struct State
    {
      // Right side of the rule containing a pointer to a grammar production
      const GProduction *rhs;
      // Source colummn
      u64 start;
      // Left side of the rule containing a non-terminal
      NT lhs;
      // Index where the dot is located inside production
      u8 dot;

      State() : rhs(nullptr) {}
      State(NT lhs, const GProduction *rhs, u8 dot, u64 start) : rhs(rhs), start(start), lhs(lhs), dot(dot) {}

      /**
       * \brief Returns whether dot has reached the end of production.
       */
      bool is_complete() const;

      /**
       * \brief Returns the symbol right after the dot.
       */
      const std::optional<GSymbol> next_symbol() const;

      bool operator==(const State &other) const
      {
        return lhs == other.lhs &&
               dot == other.dot &&
               start == other.start &&
               *rhs == *other.rhs;
      }

      const std::string to_string() const
      {
        std::string sb = jc::to_string(lhs) + " -> ";
        for (u8 i = 0; i < rhs->size; i++)
        {
          if (i == dot)
            sb += "• ";
          GSymbol aux = rhs->data.at(i);
          sb += aux.to_string() + ' ';
        }
        if (dot == rhs->size)
          sb += "•";
        sb += " [" + std::to_string(start) + "]";
        return sb;
      }
    };

    struct StateHash
    {
      std::size_t operator()(const State &s) const noexcept
      {
        std::size_t h = std::hash<int>{}(static_cast<int>(s.lhs));
        h ^= std::hash<jc::u8>{}(s.dot) + 0x9e3779b9 + (h << 6) + (h >> 2);
        h ^= std::hash<jc::u64>{}(s.start) + 0x9e3779b9 + (h << 6) + (h >> 2);
        h ^= std::hash<const jc::grammar::GProduction *>{}(s.rhs) + 0x9e3779b9 + (h << 6) + (h >> 2);
        return h;
      }
    };

    using StateSet = std::unordered_set<State, StateHash>;

    struct DFSEdge
    {
      State state;
      u64 finish;
    };

    struct PTNode
    {
      grammar::NT rule;
      std::vector<std::unique_ptr<struct PTree>> children;
    };

    struct PTree
    {
      std::variant<std::optional<Token>, PTNode> value;
    };

    using DFSNode = std::vector<DFSEdge>;

    /**
     * \brief Parser responsible for recognizing and validating the source code
     *
     * This parser uses the Earley Algorithm, a strategy developed by Jay Earley (1968) that can handle
     * basically all context-free grammars, including the left-recursive ones.
     */
    class Parser
    {
    private:
      // The symbol table generated by lexer
      SymbolTable symbols;
      // List of parser errors captured during the parsing
      std::vector<ParserError> errors;
      // Avoiding type "grammar::grammar" everytime inside the Parser...
      const Grammar *grammar = &grammar::grammar;
      ast::NodePtr ast_root;

      void add_error(u64 pos, u32 line, const std::string &msg, const std::string &found, const std::string &expected)
      {
        errors.emplace_back(pos, line, msg, found, expected);
      }

      /**
       * \brief The "scan" step on Earley Parsing. During this stage, the Parser recognizes the next symbol as a token
       * and advances the dot to right, adding the updated item to the next chart's column.
       * \param chart The chart, represented as a vector of states
       * \param state The current item
       * \param symbol The recognized symbol
       * \param it The current column of the chart (iteration)
       * \param tokens List of all the tokens
       *
       * \return Boolean indicating whether the match occurred, i.e. the token matches the expected symbol.
       */
      [[nodiscard]]
      bool scan(std::vector<StateSet> &chart, const State &state, const GSymbol &symbol, u64 it, const std::vector<Token> &tokens);

      /**
       * \brief The "predict" step on Earley Parsing. During this stage, the Parser recognizes the next symbol as
       * a non-terminal and expands it: all the productions from the non-terminal are added on the current chart's column,
       * where they can be analyzed after this.

       * \param chart The chart, represented as a vector of states
       * \param state The current item
       * \param symbol The recognized symbol
       * \param it The current column of the chart (iteration)
       *
       * \return Boolean indicating whether a prediction was made, i.e., non-terminal's predictions were added to this column.
       */
      [[nodiscard]]
      bool predict(std::vector<StateSet> &chart, const State &state, const GSymbol &symbol, u64 it);

      /**
       * \brief The "complete" step on Earley Parsing. During this stage, the Parser reaches the end of the item and backtracks to
       * its original column. Then, it finds all the items whose symbol after the dot is the one that has been completed, advances to the right
       * and insert the item on current column.

       * \param chart The chart, represented as a vector of states
       * \param state The current item
       * \param symbol The recognized symbol
       * \param it The current column of the chart (iteration)
       *
       * \return Boolean indicating whether some item was added on current column.
       */
      [[nodiscard]]
      bool complete(std::vector<StateSet> &chart, const State &current_state, u64 it);

      /**
       * \brief The final step on Earley Parser. Check whether the grammar's start symbol was
       * able to produce a complete token at the end of the process.

       * \param chart The chart, represented as a vector of states
       * \param last The last column of the chart
       *
       * \return Boolean indicating whether the parser was successful.
       */
      [[nodiscard]]
      bool has_ended(const std::vector<StateSet> &chart, u64 last);

      [[nodiscard]]
      std::optional<std::vector<std::pair<u64, DFSEdge>>> dfs(
          std::function<std::vector<DFSEdge>(i64, const u64 &)> edges,
          std::function<u64(i64, const DFSEdge &)> child,
          std::function<bool(i64, const u64 &)> pred,
          const u64 &root_node);

      [[nodiscard]]
      std::vector<std::pair<u64, DFSEdge>> top_list(
          const std::vector<Token> &tokens,
          const std::vector<DFSNode> &chart,
          const DFSEdge &edge,
          u64 start);

      [[nodiscard]]
      PTree parse_tree(
          const std::vector<Token> &tokens,
          const std::vector<StateSet> &chart,
          const std::vector<std::vector<DFSEdge>> &reversed_chart);

      void print_tree(const PTree &node, int indent = 0);

      void fill_symbol_table(ast::Node &root);

    public:
      Parser() {};

      /**
       * \brief Parses context-free grammars using the Earley parsing algorithm.
       * The algorithm builds parsing states incrementally through prediction,
       * scanning, and completion operations, supporting ambiguous and
       * left-recursive grammars.
       *
       * \param tokens The list of tokens generated by the lexer.
       *
       * \return Boolean indicating whether the program is valid.
       */
      bool earley_parse(const std::vector<Token> &&tokens, bool print_ast);

      const std::vector<ParserError> &get_errors() const
      {
        return errors;
      }

      bool has_errors() const
      {
        return !errors.empty();
      }
    };
  }
}
